/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package srednia;


import javax.swing.JTextField;

/**
 *
 * @author Skrzymo
 */
public class JFrameGłówna extends javax.swing.JFrame {
    private int sumaECTS;
    private int licznikForm;
    private double sumaOcen;
    private double[] tabPrzedmioty;
    private int licznikPrzedmiotow;
    private int[] tabECTS;

    public int getLicznikPrzedmiotow() {
        return licznikPrzedmiotow;
    }

    public void setLicznikPrzedmiotow(int licznikPrzedmiotow) {
        this.licznikPrzedmiotow = licznikPrzedmiotow;
    }


    public double getSumaOcen() {
        return sumaOcen;
    }

    public void setSumaOcen(double sumaOcen) {
        this.sumaOcen = sumaOcen;
    }

    public int getLicznikForm() {
        return licznikForm;
    }

    public void setLicznikForm(int licznikForm) {
        this.licznikForm = licznikForm;
    }

    public int getSumaECTS() {
        return sumaECTS;
    }

    public void setSumaECTS(int sumaECTS) {
        this.sumaECTS = sumaECTS;
    }
    /**
     * Creates new form JFrameGłówna
     */
    public JFrameGłówna() {
        initComponents();
        this.sumaECTS = sumaECTS;
        this.licznikForm = licznikForm;
        this.sumaOcen = sumaOcen;
        tabPrzedmioty = new double[100];
        this.licznikPrzedmiotow = licznikPrzedmiotow;
        tabECTS = new int[100];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dodajPrzedmiot = new javax.swing.JButton();
        wyklad = new javax.swing.JButton();
        wyliczSrednia = new javax.swing.JButton();
        ocena = new javax.swing.JTextField();
        przedmiot = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        poleGlowne = new javax.swing.JTextArea();
        ects = new javax.swing.JTextField();
        cwiczenia = new javax.swing.JButton();
        laboratorium = new javax.swing.JButton();
        pracownia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Program liczący średnią ważoną ocen");

        dodajPrzedmiot.setText("Dodaj przedmiot");
        dodajPrzedmiot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajPrzedmiotActionPerformed(evt);
            }
        });

        wyklad.setText("Wykład");
        wyklad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wykladActionPerformed(evt);
            }
        });

        wyliczSrednia.setText("Wylicz średnią");
        wyliczSrednia.setToolTipText("");
        wyliczSrednia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyliczSredniaActionPerformed(evt);
            }
        });

        ocena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ocena.setText("Ocena");
        ocena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocenaActionPerformed(evt);
            }
        });

        przedmiot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        przedmiot.setText("Nazwa przedmiotu");

        poleGlowne.setColumns(20);
        poleGlowne.setRows(5);
        jScrollPane1.setViewportView(poleGlowne);

        ects.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ects.setText("Liczba ECTS");

        cwiczenia.setText("Ćwiczenia");
        cwiczenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cwiczeniaActionPerformed(evt);
            }
        });

        laboratorium.setText("Laboratorium");
        laboratorium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratoriumActionPerformed(evt);
            }
        });

        pracownia.setText("PS");
        pracownia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pracowniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dodajPrzedmiot, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(przedmiot, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ects, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(laboratorium)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pracownia))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(wyklad)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cwiczenia)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ocena, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(wyliczSrednia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(przedmiot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodajPrzedmiot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(wyklad)
                                    .addComponent(cwiczenia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pracownia)
                                    .addComponent(laboratorium)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(ocena))))
                    .addComponent(wyliczSrednia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajPrzedmiotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajPrzedmiotActionPerformed
        poleGlowne.setText(poleGlowne.getText()+przedmiot.getText()+" ECTS: "+ects.getText()+"\n");
        int a = Integer.parseInt(ects.getText());
        addECTS(a);
        wyliczSredniaPrzedmiotu(a);
        zerujLicznikForm();
        zerujSumeOcen();
        addPrzedmiot();
    }//GEN-LAST:event_dodajPrzedmiotActionPerformed

    private void wykladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wykladActionPerformed
        poleGlowne.setText(poleGlowne.getText()+"Wykład: "+ocena.getText()+"\n");
        double a = Double.parseDouble(ocena.getText());
        addForm();
        sumujOceny(a);
    }//GEN-LAST:event_wykladActionPerformed

    private void ocenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocenaActionPerformed

    private void cwiczeniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cwiczeniaActionPerformed
        poleGlowne.setText(poleGlowne.getText()+"Ćwiczenia: "+ocena.getText()+"\n");
        double a = Double.parseDouble(ocena.getText());
        addForm();
        sumujOceny(a);
    }//GEN-LAST:event_cwiczeniaActionPerformed

    private void laboratoriumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratoriumActionPerformed
        poleGlowne.setText(poleGlowne.getText()+"Laboratorium: "+ocena.getText()+"\n");
        double a = Double.parseDouble(ocena.getText());
        addForm();
        sumujOceny(a);
    }//GEN-LAST:event_laboratoriumActionPerformed

    private void pracowniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pracowniaActionPerformed
        poleGlowne.setText(poleGlowne.getText()+"Pracownia specjalistyczna: "+ocena.getText()+"\n");
        double a = Double.parseDouble(ocena.getText());
        addForm();
        sumujOceny(a);
    }//GEN-LAST:event_pracowniaActionPerformed

    private void wyliczSredniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyliczSredniaActionPerformed
        int a = Integer.parseInt(ects.getText());
        wyliczSredniaPrzedmiotu(a);
        poleGlowne.setText(poleGlowne.getText()+srednia());
    }//GEN-LAST:event_wyliczSredniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGłówna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGłówna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGłówna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGłówna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGłówna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cwiczenia;
    private javax.swing.JButton dodajPrzedmiot;
    private javax.swing.JTextField ects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton laboratorium;
    private javax.swing.JTextField ocena;
    private javax.swing.JTextArea poleGlowne;
    private javax.swing.JButton pracownia;
    private javax.swing.JTextField przedmiot;
    private javax.swing.JButton wyklad;
    private javax.swing.JButton wyliczSrednia;
    // End of variables declaration//GEN-END:variables

    private void addECTS(int a) {
        setSumaECTS(getSumaECTS()+a);
        tabECTS[getLicznikPrzedmiotow()+1] = a;
    }
    
    private void zerujLicznikForm() {
        setLicznikForm(0);
    }
    
    private void addForm() {
        setLicznikForm(getLicznikForm()+1);
    }
    
    private void sumujOceny(double ocena) {
        setSumaOcen(getSumaOcen()+ocena);
    }
    
    private void zerujSumeOcen() {
        setSumaOcen(0);
    }
    
    private void wyliczSredniaPrzedmiotu(int ects) {
        double srednia = (getSumaOcen()/getLicznikForm());
        double przedmiot = srednia*tabECTS[getLicznikPrzedmiotow()];
        tabPrzedmioty[getLicznikPrzedmiotow()] = przedmiot;
        
    }
    
    private void addPrzedmiot() {
        setLicznikPrzedmiotow(getLicznikPrzedmiotow()+1);
    }
    
    private double srednia() {
        double suma = 0;
        for (int i = 1 ; i<=getLicznikPrzedmiotow() ; i++)
            suma+=tabPrzedmioty[i];
        double srednia = suma/getSumaECTS();
        return srednia;
    }
}
